name: build java native image
on:
  push:
    branches: [ "main" ]
jobs:
  build-java:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm-community'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: env
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: native image
        run: gradle nativeCompile
      - name: Find all files
        run: |
            find build/
      - name: run
        run: |
            ./build/native/nativeCompile/github_workflow_action_tutorial.java

